name: price_service_client
description: A Dart SDK for pyth price service client.
version: 1.0.0
repository: https://github.com/jovinlidan/price-service-client-dart

environment:
  sdk: ^3.9.0

dependencies:
  price_service_sdk: ^1.0.0
  logger: ^2.6.1
  dio: ^5.9.0
  args: ^2.7.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
